development:
  :concurrency: 5
production:
  :concurrency: 20
:queues:
  - default
  - mailers

:schedule:
  refresh_token:
    cron: '0 */10 * * * *'
    class: RefreshWorker
  test:
    cron: '0 * * * * *'  
    class: TestWorker
